export const company = {
    name: 'CODURA',
    alias: 'Codura',
    slug: 'codura',
    phone: '',
    phone_label: '',
    email: '',
    address: '',
    wa: '',
    yt: '',
    ig: '',
    fb: '',
    tw: 'https://x.com/fortivault87827',
    github: 'https://github.com/sbymaster/codura',
    linkedin: '',
};