export const company = {
    name: 'FORTIVAULT',
    alias: 'FORTIVAULT',
    slug: 'fortivault',
    phone: '',
    phone_label: '',
    email: '',
    address: '',
    wa: '#',
    yt: '#',
    ig: '#',
    fb: '#',
    tw: '#',
    linkedin: '#',
};

export const msgDummy = [
    { is_me: true, text: 'How does Fortivault ensure the security of my smart contracts?' },
    { is_me: false, text: 'Fortivault leverages advanced artificial intelligence algorithms and blockchain auditing tools to provide unparalleled security for your smart contracts. Our AI analyzes code vulnerabilities, detects potential exploits, and offers automated fixes, ensuring your contracts are robust and future-proof. With Fortivault, you can confidently protect your digital assets and focus on innovation' },
    { is_me: true, text: 'Can Fortivault integrate with my existing blockchain projects?' },
    { is_me: false, text: 'Absolutely! Fortivault is designed to seamlessly integrate with major blockchain platforms, including Ethereum, Solana, Binance Smart Chain, and more. Our flexible APIs and developer-f,riendly tools ensure a smooth onboarding process, so you can enhance the security of your projects without disrupting your workflow.' },
    { is_me: true, text: 'What makes Fortivault different from other smart contract tools?' },
    { is_me: false, text: `Fortivault stands out by combining state-of-the-art AI with industry-leading blockchain expertise. Unlike traditional tools, we don’t just identify vulnerabilities—we fix them for you in real-time. Plus, our continuous monitoring feature ensures your contracts remain secure even after deployment. With Fortivault, you're not just securing your contracts; you're securing your future.` },
    { is_me: true, text: 'How does Fortivault ensure the security of my smart contracts?' },
    { is_me: false, text: 'Fortivault leverages advanced artificial intelligence algorithms and blockchain auditing tools to provide unparalleled security for your smart contracts. Our AI analyzes code vulnerabilities, detects potential exploits, and offers automated fixes, ensuring your contracts are robust and future-proof. With Fortivault, you can confidently protect your digital assets and focus on innovation' },
    { is_me: true, text: 'How does Fortivault ensure the security of my smart contracts?' },
    { is_me: false, text: 'Absolutely! Fortivault is designed to seamlessly integrate with major blockchain platforms, including Ethereum, Solana, Binance Smart Chain, and more. Our flexible APIs and developer-friendly tools ensure a smooth onboarding process, so you can enhance the security of your projects without disrupting your workflow.' },
    { is_me: true, text: 'How does Fortivault ensure the security of my smart contracts?' },
    { is_me: false, text: `Absolutely! Fortivault is designed to seamlessly integrate with major blockchain platforms, including Ethereum, Solana, Binance Smart Chain, and more. Our flexible APIs and developer-friendly tools ensure a smooth onboarding process, so you can enhance the security of your projects without disrupting your workflow.` },
];

export const historyDummy = [
    `Exploring Fortivault's Smart Contract Security`,
    `How Fortivault Protects My Assets`,
    `Making Blockchain Safer with Fortivault`,
    `Exploring Fortivault's Smart Contract Security`,
    `How Fortivault Protects My Assets`,
    `Making Blockchain Safer with Fortivault`,
    `Exploring Fortivault's Smart Contract Security`,
    `How Fortivault Protects My Assets`,
    `Making Blockchain Safer with Fortivault`,
    `Exploring Fortivault's Smart Contract Security`,
    `How Fortivault Protects My Assets`,
    `Making Blockchain Safer with Fortivault`,
]