export const company = {
    name: 'FORTIVAULT',
    alias: 'FORTIVAULT',
    slug: 'fortivault',
    phone:'',
    phone_label:'',
    email:'',
    address:'',
    wa:'#',
    yt:'#',
    ig:'#',
    fb:'#',
    tw:'#',
    linkedin:'#',
};