export const company = {
    name: 'CODURA',
    alias: 'CODURA',
    slug: 'codura',
    phone:'',
    phone_label:'',
    email:'',
    address:'',
    wa:'',
    yt:'',
    ig:'',
    fb:'',
    tw:'https://x.com/CoduraTech',
    linkedin:'',
};